package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/guacsec/guac/pkg/assembler/graphql/model"
)

// IngestJenkins is the resolver for the ingestJenkins field.
func (r *mutationResolver) IngestJenkins(ctx context.Context, jenkins model.JenkinsInputSpec) (*model.Jenkins, error) {
	return r.Backend.IngestJenkins(ctx, jenkins)
}

// Jenkins is the resolver for the jenkins field.
func (r *queryResolver) Jenkins(ctx context.Context, jenkinsSpec *model.JenkinsSpec) ([]*model.Jenkins, error) {
	return r.Backend.Jenkins(ctx, jenkinsSpec)
}
